<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>author</key>
	<string>Koroshiya</string>
	<key>bundleUUID</key>
	<string>0F24FCF1-6543-4CC6-8B33-2EAED401FE3D</string>
	<key>comment</key>
	<string>To make RenpyLanguage the default for Renpy files, open a .rpy file and select View|Syntax|Open all with current extension as...|RenpyLanguage.</string>
	<key>fileTypes</key>
	<array>
		<string>rpy</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\bpython[0-9.-]*\b</string>
	<key>foldingStartMarker</key>
	<string>^\s*(def|class)\s+([.a-zA-Z0-9_ &lt;]+)\s*(\((.*)\))?\s*:|\{\s*$|\(\s*$|\[\s*$|^\s*"""(?=.)(?!.*""")</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>RenpyLanguage</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>renpy transform keywords</string>
			<key>match</key>
			<string>\b(fade|dissolve|pixellate|move|moveinright|moveinleft|moveintop|moveinbottom|moveoutright|moveoutleft|moveouttop|moveoutbottom|ease|easeinright|easeinleft|easeintop|easeinbottom|easeoutright|easeoutleft|easeouttop|easeoutbottom|zoomin|zoomout|zoominout|vpunch|hpunch|blinds|squares|wipeleft|wiperight|wipeup|wipedown|slideleft|slideright|slideup|slidedown|slideawayleft|slideawayright|slideawayup|slideawaydown|irisin|repeat|transform|fadein|fadeout|position|Position|easein|easeout|time|align|xalign|yalign|ui)\b</string>
			<key>name</key>
			<string>keyword.control.flow.renpy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>renpy transform properties</string>
			<key>match</key>
			<string>\b(pos|xpos|ypos|anchor|xanchor|yanchor|align|xalign|yalign|xoffset|yoffset|xcenter|ycenter|rotate|rotate_pad|transform_anchor|zoom|xzoom|yzoom|nearest|alpha|additive|around|alignaround|angle|radius|crop|crop_relative|corner1|corner2|size|subpixel|delay|events|kind|color|action|area|hovered|unhovered|idle|hover|ground|python|clicked|modal|text_style|default|spacing|yminimum|xminimum|ymaximum|xmaximum|has|who|what|tag|value|theme)\b</string>
			<key>name</key>
			<string>variable.parameter.function.language.python</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>renpy show statement keywords</string>
			<key>match</key>
			<string>\b(as|at|behind|onlayer|zorder|expression|music|sound|movie|pause|clear|hide|show|scene|image)\b</string>
			<key>name</key>
			<string>keyword.control.flow.renpy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>renpy python keywords</string>
			<key>match</key>
			<string>\b(python|renpy|store|init|define|jump|label)\b</string>
			<key>name</key>
			<string>keyword.control.flow.renpy</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>renpy methods</string>
			<key>match</key>
			<string>\b(Character|DynamicCharacter|Pause|Dissolve|Fade|Position|At|Text|Hide|Jump|NullAction|Return|ShowTransient|SetDict|SetField|SetScreenVariable|SetVariable|ToggleDict|ToggleField|ToggleScreenVariable|ToggleVariable|MainMenu|Quit|ShowMenu|Start|FileAction|FileDelete|FileLoad|FilePage|FilePageNext|FilePagePrevious|FileSave|FileTakeScreenshot|QuickLoad|QuickSave|Play|Queue|SetMixer|Stop|Function|Help|HideInterface|If|InvertSelected|MouseMove|Notify|OpenURL|RollForward|Rollback|Screenshot|SelectedIf|SensitiveIf|Skip|With|AnimatedValue|DictValue|FieldValue|MixerValue|StaticValue|VariableValue|XScrollValue|YScrollValue|Preference|FileCurrentPage|FileCurrentScreenshot|FileJson|FileLoadable|FileNewest|FilePageName|FileSaveName|FileScreenshot|FileSlotName|FileTime|FileUsedSlots|SideImage|Tooltip|Action|Gallery|LiveComposite|Movie|Transform)\b</string>
			<key>name</key>
			<string>support.function.builtin.python</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.python.renpy</string>
	<key>uuid</key>
	<string>11B0273F-0284-4483-B17B-4B8D0A9294CD</string>
</dict>
</plist>
